### ISSUE TITLE
运行docker后,响应出错 Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by drowning-in-codes** [xiangsx/gpt4free-ts#100]
## 描述
使用docker镜像成功运行后
 向网站发送请求,但响应出现问题 
Error: failed to do request:....i/o timeout (Client.Timeout exceeded while awaiting headers)
使用的默认网站和模型
 `curl "http://xxxx.com/ask/stream?prompt=hello"`
返回响应`{"error":{"message":"failed to do request: Get \"https://you.com/api/streamingSearch?q=hello&page=1&count=10&safeSearch=Moderate&onShoppingPage=False&mkt=&responseFilter=WebPages%2CTranslations%2CTimeZone%2CComputation%2CRelatedSearches&domain=youchat&queryTraceId=4878f9fd-28af-4460-9e59-7de941fed03d&chat=%5B%5D\": dial tcp 202.160.128.238:443: i/o timeout (Client.Timeout exceeded while awaiting headers)"}}`

这应该不是代理问题,感觉是you网站的captch没有解决造成超时,但其他网站也基本会报错
## 截图
成功运行docker镜像
![image](https://github.com/xiangsx/gpt4free-ts/assets/60743790/d59afeee-133a-4e66-8be8-76e1309226ee)
相应报错
![image](https://github.com/xiangsx/gpt4free-ts/assets/60743790/5adea2ac-1e9c-4ed0-88f4-2b6ff32d8b61)
`docker logs -f`
![image](https://github.com/xiangsx/gpt4free-ts/assets/60743790/b2442735-87f5-424f-acf4-24ab114f695f)
## 环境 
阿里云 大陆

**Comment by sorker** [comment]
解决了吗

**Comment by drowning-in-codes** [comment]
> 解决了吗
> 

我怀疑是我服务器内存太小的问题

**Comment by drowning-in-codes** [comment]
我把其他耗内存的服务关掉之后正常了

**Comment by sorker** [comment]
好的 谢谢

在 2023年11月10日，18:45，QiuhaoS ***@***.***> 写道：

﻿

我把其他耗内存的服务关掉之后正常了
