### ISSUE TITLE
监听3000的端口后，还是提示Need apikey for TempMail

### ISSUE THREAD

**Issue by xiaoyao20084321** [xiangsx/gpt4free-ts#29]
群主大大，运行yarn start后，监听了3000的端口，浏览器输入http://127.0.0.1:3000/ask?prompt=你好，然后终端提示Need apikey for TempMail。意思是说要在http://127.0.0.1:3000/ask?prompt=你好   这里在添加apiKey=xxxx？

**Comment by xiaoyao20084321** [comment]
如果是本地运行的话，只需要在项目根目录创建一个. env文件，然后写入和docker一样的数据就行

**Comment by rabotone** [comment]
> 如果是本地运行的话，只需要在项目根目录创建一个. env文件，然后写入和docker一样的数据就行

具体是写什么，我不太懂

**Comment by xiaoyao20084321** [comment]
> > 如果是本地运行的话，只需要在项目根目录创建一个. env文件，然后写入和docker一样的数据就行
> 
> 具体是写什么，我不太懂
看README里面 <img width="915" alt="image" src="https://github.com/xiangsx/gpt4free-ts/assets/10344550/7f175e8a-89a9-4bd3-966f-9958b1fe79e6">
