### ISSUE TITLE
Error: Error while obtaining verfication URL!

### ISSUE THREAD

**Issue by ottocsb** [xiangsx/gpt4free-ts#33]
you model is normal, but the forefront error prompts:
try find text input
not found text input.
try register
Error: Error while obtaining verfication URL!

**Comment by xqymain** [comment]
same problem. it seems that no mail was received.

**Comment by RipperTs** [comment]
I also have the same problem
`Error: Error while obtaining verfication URL!`

`TempEmailType.TempEmail` or `TempEmailType.TempEmail44`

**Comment by DNLINYJ** [comment]
the temp email service have some problems, wait for fix

**Comment by xiangsx** [comment]
现在重试下
