### ISSUE TITLE
使用forefront出错：TimeoutError: Waiting for selector 

### ISSUE THREAD

**Issue by MinhuaHuang** [xiangsx/gpt4free-ts#36]
- 问题描述：

本地启动项目，使用you没问题，使用forefront出错，env设置了rapid_api_key

- 控制台输出信息：

```
try find text input
try to find input
found
1
TimeoutError: Waiting for selector `.flex-1 > .flex:nth-child(1) > .relative > .grid > .post-markdown` failed: Waiting failed: 30000ms exceeded
    at Timeout.<anonymous> (/Users/xxxx/Work/gpt4free-ts/node_modules/puppeteer-core/src/common/WaitTask.ts:91:11)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

**Comment by xiangsx** [comment]
现在试下

**Comment by lucasmanea21** [comment]
I'm still running into the same issue here.

**Comment by lucasmanea21** [comment]
> > I'm still running into the same issue here.
> 
> try again now

Thanks 🙏

I'm now running into this, not sure if it's a problem from my side (it probably is?)

```
  cause: Error: getaddrinfo ENOTFOUND host
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'host'
  }
}
```

**Comment by xiangsx** [comment]
> > > I'm still running into the same issue here.
> > 
> > 
> > try again now
> 
> Thanks 🙏
> 
> I'm now running into this, not sure if it's a problem from my side (it probably is?)
> 
> ```
>   cause: Error: getaddrinfo ENOTFOUND host
>       at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
>     errno: -3008,
>     code: 'ENOTFOUND',
>     syscall: 'getaddrinfo',
>     hostname: 'host'
>   }
> }
> ```

yes

**Comment by TAEGANJERRIE** [comment]
you can try again now
