### ISSUE TITLE
Websites to reverse

### ISSUE THREAD

**Issue by Nebelung-Dev** [xiangsx/gpt4free-ts#41]
Here is some:
- https://ai.mcbbs.gq
- https://www.promptboom.com
- https://521.zeabur.app
- https://a.aiask.me
- https://ai.gptforlove.com
- https://ai.gogpt.site
- https://aichat.gogpt.site
- https://d2.betai55.uk
- https://vvanglro.eu.org
- https://gpt4.gravityengine.cc
- https://f12.xjai.cc
- https://chat2.xeasy.me
- https://gpt.xeasy.me
- https://chat.51buygpt.com
- https://trychatgp.com

**Comment by MartinMelville** [comment]
????
