### ISSUE TITLE
网页提示Not Found

### ISSUE THREAD

**Issue by Chr1s-T** [xiangsx/gpt4free-ts#47]
使用yarn start之后 网页提示Not Found，没有其他任何显示。
![image](https://github.com/xiangsx/gpt4free-ts/assets/23159278/2afd5775-02ac-4f59-b073-f72b1067ae41)

**Comment by xiangsx** [comment]
输入完整的url，这个项目只是提供了个接口 并没有web页面

**Comment by brandoncamerer** [comment]
完整的URL是什么？

**Comment by ikimiler** [comment]
> 完整的URL是什么？

具体的接口请求

**Comment by Chr1s-T** [comment]
> > 完整的URL是什么？
> 
> 具体的接口请求

readme文档里面都写了，问题关闭

**Comment by alexallen1** [comment]
同问，Not Found

**Comment by alexallen1** [comment]
Lack of empathy
