### ISSUE TITLE
如果要部署在海外VPS上，不想用proxy怎么配置？谢谢！

### ISSUE THREAD

**Issue by goldenhawksu** [xiangsx/gpt4free-ts#5]

**Comment by xiangsx** [comment]
那就不用配置

**Comment by xiangsx** [comment]
配置个rapid_api_key即可

**Comment by goldenhawksu** [comment]
我的意思是，.env文件里应该怎么定义？
只修改api的值，第一行不用动？

**Comment by xiangsx** [comment]
> 我的意思是，.env文件里应该怎么定义？ 只修改api的值，第一行不用动？

删掉第一行

**Comment by goldenhawksu** [comment]
尝试了两种方式，
1. 不用proxy，删掉.env的第一行，输入以下命令行(docker端口是8080)，
/gpt4free-ts# curl "http://127.0.0.1:8080/ask?prompt=hello&model=forefront&gptmodel=gpt-4&resignup=0"
得到以下回复：
{"message":"Request failed with status code 403"}

2. 使用proxy，输入同样命令行，得到回复如下，
 {"message":"Failed to create account! sign email res parse token failed!"}

问题出在那里？

**Comment by xiangsx** [comment]
> 尝试了两种方式，
> 
> 1. 不用proxy，删掉.env的第一行，输入以下命令行(docker端口是8080)，
>    /gpt4free-ts# curl "http://127.0.0.1:8080/ask?prompt=hello&model=forefront&gptmodel=gpt-4&resignup=0"
>    得到以下回复：
>    {"message":"Request failed with status code 403"}
> 2. 使用proxy，输入同样命令行，得到回复如下，
>    {"message":"Failed to create account! sign email res parse token failed!"}
> 
> 问题出在那里？

更新代码，重试 1.不用proxy，然后把返回贴出来看看

**Comment by xiangsx** [comment]
大概率邮箱问题，检查这里有没有订阅

https://rapidapi.com/calvinloveland335703-0p6BxLYIH8f/api/temp-mail44

**Comment by goldenhawksu** [comment]
> > 尝试了两种方式，
> > 
> > 1. 不用proxy，删掉.env的第一行，输入以下命令行(docker端口是8080)，
> >    /gpt4free-ts# curl "http://127.0.0.1:8080/ask?prompt=hello&model=forefront&gptmodel=gpt-4&resignup=0"
> >    得到以下回复：
> >    {"message":"Request failed with status code 403"}
> > 2. 使用proxy，输入同样命令行，得到回复如下，
> >    {"message":"Failed to create account! sign email res parse token failed!"}
> > 
> > 问题出在那里？
> 
> 更新代码，重试 1.不用proxy，然后把返回贴出来看看

更新了代码，用proxy方式，订阅了邮件，输入命令行以后得到一个空的回答，像下面这样，正反大括号，空字符串
{}

**Comment by xiangsx** [comment]
更新代码试试

**Comment by goldenhawksu** [comment]
更新了刚刚的代码，forefront 和 you 返回都是 {}

**Comment by xiangsx** [comment]
更新代码，resignup传1

**Comment by goldenhawksu** [comment]
结果如下，
curl: (18) transfer closed with 2 bytes remaining to read

**Comment by KaishuaiXu** [comment]
yarn返回“Error: Need apikey for TempMail”

**Comment by HuanLinOTO** [comment]
> yarn返回“Error: Need apikey for TempMail”

你翻译一下就知道了...

**Comment by xiaoyao20084321** [comment]
> > yarn返回“错误：TempMail需要apikey”
> 
> 你翻译一下就知道了...

为啥翻译一下就知道了。。

**Comment by HuanLinOTO** [comment]
> > > yarn返回“错误：TempMail需要apikey”
> > 
> > 
> > 你翻译一下就知道了...
> 
> 为啥翻译一下就知道了。。

缺 APIKey 啊

**Comment by zhanghongyong123456** [comment]
> > > > yarn返回“错误：TempMail需要apikey”
> > > 
> > > 
> > > 你翻译一下就知道了...
> > 
> > 
> > 为啥翻译一下就知道了。。
> 
> 缺 APIKey 啊

大佬你那个项目库怎么用呢，属于新手，完全不懂，能出一个gpt4free-ts关于使用你项目获取api-key相关的教程吗，谢谢大佬

**Comment by IdaBruce** [comment]
No description provided.

**Comment by goldenhawksu** [comment]
用docker部署，和其它人遇到一样的问题，forefront模型不能用了，那也等于没有gpt4可以用了.......
