### ISSUE TITLE
forefront.ai 注册失败了

### ISSUE THREAD

**Issue by jmluang** [xiangsx/gpt4free-ts#55]
提示：Sign up unsuccessful due to failed security validations. Please refresh the page to try again or reach out to support for more assistance.

temp-email44，tempmail-lol 都是这个提示，不注册成功其他model用不了。

有其他办法在 forefront 注册失败的情况下用其他 model 嘛？

**Comment by xiangsx** [comment]
入群细说

**Comment by tangxiaohong0082** [comment]
你好，群的号码是什么
