### ISSUE TITLE
forefront 目前还是已经不支持？ 

### ISSUE THREAD

**Issue by chechuangfeng** [xiangsx/gpt4free-ts#6]
curl "http://127.0.0.1:3000/ask?prompt=hello&model=forefront&gptmodel=gpt-4&resignup=0"
{"message":"Cannot read properties of undefined (reading 'status')"}%

**Comment by xiangsx** [comment]
更新代码再试试

**Comment by chechuangfeng** [comment]
> 更新代码再试试

 curl "http://127.0.0.1:3000/ask/stream?prompt=hi&model=forefront&gptmodel=gpt-4&resignup=0"
{}%

更新后不报错，但是个空的json

**Comment by xiangsx** [comment]
看看日志里面有报错吗

**Comment by chechuangfeng** [comment]
<img width="585" alt="image" src="https://user-images.githubusercontent.com/3196849/236672030-7d9c0dee-5a88-437e-babc-1dfa5b2f2cb4.png">


> 看看日志里面有报错吗

**Comment by xiangsx** [comment]
启动之后第一次请求大概多少秒返回的，如果时间很长大概5~10秒，那大概率是成功了，打点日志自己调试一下吧，找到问题和我说一下

**Comment by xiangsx** [comment]
![image](https://user-images.githubusercontent.com/29322721/236672358-c4c7aa7c-7260-41a6-a74c-0b32ef976222.png)
我刚试了下 还是完全正常的

**Comment by chechuangfeng** [comment]
> ![image](https://user-images.githubusercontent.com/29322721/236672358-c4c7aa7c-7260-41a6-a74c-0b32ef976222.png) 我刚试了下 还是完全正常的

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/3196849/236673810-413bac85-1473-469c-a23b-43632980c3bf.png">
启动后第一次是可以的。第二次就不行了。

这个是有次数限制？

**Comment by huankong233** [comment]
我也返回了空json，尝试输出数据，但是都没有东西

![image](https://user-images.githubusercontent.com/49610758/236673834-e6782891-62e8-4719-8c64-4726984cfc90.png)

**Comment by xiangsx** [comment]
稍等我看看能不能复现，我这边正常的

**Comment by xiangsx** [comment]
更新代码 兄弟们

**Comment by xiangsx** [comment]
重新更新下。刚提交错了

**Comment by huankong233** [comment]
> 
![image](https://user-images.githubusercontent.com/49610758/236676288-06bb27d5-cecd-4747-9e1a-9ac5cf401ea4.png)
悲

**Comment by huankong233** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/49610758/236676288-06bb27d5-cecd-4747-9e1a-9ac5cf401ea4.png) 悲

秒返回的

**Comment by xiangsx** [comment]
更新代码，resignup传1

**Comment by rabotone** [comment]
Error: Need apikey for TempMail
    at new TempMail44 (G:\gpt4free-ts-master\utils\emailFactory.ts:132:19)
    at CreateEmail (G:\gpt4free-ts-master\utils\emailFactory.ts:15:20)
    at Forefrontnew.<anonymous> (G:\gpt4free-ts-master\model\forefront\index.ts:65:41)
    at Generator.next (<anonymous>)
    at fulfilled (G:\gpt4free-ts-master\model\forefront\index.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by rabotone** [comment]
这个报错什么原因

**Comment by TuanZiGit** [comment]
```
event: error
data: {"error":"you not support model forefront"}
```
`resignup=0` 情况下会报错
