### ISSUE TITLE
    "error": "you not support model forefront"

### ISSUE THREAD

**Issue by myrisc** [xiangsx/gpt4free-ts#68]
这是怎么了？

**Comment by LeonardBarton** [comment]
why?

**Comment by jiaxin8211** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by xiangsx** [comment]
> 为了赚钱， forefront有GPT4, 作者删了 才能有人掏钱去用gptgod.site

真不是为了赚钱，我一公开第二天指定被封

**Comment by xiangsx** [comment]
目前可以使用其他的3.5模型
